FROM node:16-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du code
COPY . .

# Variables d'environnement pour la base de données
ENV DB_HOST=db \
    DB_USER=root \
    DB_PASSWORD=root \
    DB_NAME=pfedb

EXPOSE 3000

CMD ["node", "server.js"]
