FROM node:20-alpine as build

WORKDIR /app

# Copier uniquement les fichiers nécessaires pour npm install
COPY package*.json ./
RUN npm install --production --legacy-peer-deps

# Copier le reste des fichiers
COPY . .
RUN npm run build

# Étape de production avec Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Nettoyage
RUN rm -rf /usr/share/nginx/html/node_modules

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
