FROM node:16-alpine as build

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install react-router-dom
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

# Build de l'application
COPY . .
RUN npm run build

# Configuration nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
